# --- HARDWARE & MEMORY ---
CONFIG_BOARD_FLASH_SIZE := 2
CONFIG_BL602_USE_ROM_DRIVER := 1

# --- NETWORK STACK ---
CONFIG_BL602_WIFI_ENABLE := 1
CONFIG_RF := 1
CONFIG_PLIN := 1
CONFIG_LHAL := 1
CONFIG_MQTT := 1
CONFIG_LIB_CJSON := 1        # JSON Parser
CONFIG_LWIP := 1

# --- BLUETOOTH (BLE) ---
CONFIG_BT := 1
CONFIG_BL602_BLE_ENABLE := 1
CONFIG_BT_PERIPHERAL := 1
CONFIG_BT_CENTRAL := 0

# --- STORAGE & DRIVERS ---
CONFIG_EASYFLASH_ENABLE := 1
CONFIG_PARTITION := 1
CONFIG_BFLB_MTD := 1
CONFIG_LIBHAL := 1
CONFIG_HAL_DRV_WDT := 1      # Watchdog Timer

# --- SYSTEM & LOG ---
CONFIG_SYS_APP_TASK_STACK_SIZE := 4096
CONFIG_SYS_BLOG_ENABLE := 1
LOG_ENABLED_COMPONENTS := blog_testc hosal loopset looprt bloop